common:
  run_label: "run_1"
  log_freq: 500
  auto_resume: true
  mixed_precision: true
dataset:
  root_train: "/mnt/imagenet/training"
  root_val: "/mnt/imagenet/validation"
  name: "imagenet"
  category: "classification"
  train_batch_size0: 128
  val_batch_size0: 100
  eval_batch_size0: 100
  workers: 4
  persistent_workers: false
  pin_memory: true
image_augmentation:
  random_resized_crop:
    enable: true
    interpolation: "bilinear"
  random_horizontal_flip:
    enable: true
sampler:
  name: "variable_batch_sampler"
  vbs:
    crop_size_width: 224
    crop_size_height: 224
    max_n_scales: 5
    min_crop_size_width: 128
    max_crop_size_width: 256
    min_crop_size_height: 128
    max_crop_size_height: 256
    check_scale: 32
loss:
  category: "classification"
  classification:
    name: "label_smoothing"
    label_smoothing_factor: 0.1
optim:
  name: "sgd"
  weight_decay: 4.e-5
  no_decay_bn_filter_bias: true
  sgd:
    momentum: 0.9
    nesterov: true
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 300
  warmup_iterations: 7500
  warmup_init_lr: 0.05
  cosine:
    max_lr: 0.4
    min_lr: 2.e-4
model:
  classification:
    name: "mobilenetv2"
    activation:
      name: "relu6" # specify the activation function that you want to use in the classification network
    classifier_dropout: 0.2
    mobilenetv2:
      width_multiplier: 1.0
  normalization:
    name: "batch_norm_2d"
    momentum: 0.1
  activation:
    name: "relu" # If specific activation function is not specified, this one will be used as a default
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
    conv_weight_std: false
ema:
  enable: true
  momentum: 0.0005
ddp:
  enable: true
  rank: 0
  world_size: -1
  dist_port: 30786
stats:
  name: [ "loss", "top1", "top5" ]
  checkpoint_metric: "top1"
  checkpoint_metric_max: true