common:
  run_label: "run_1"
  log_freq: 500
  auto_resume: true
  mixed_precision: true
  tensorboard_logging: false
dataset:
  root_train: "/mnt/imagenet/training"
  root_val: "/mnt/imagenet/validation"
  name: "imagenet"
  category: "classification"
  train_batch_size0: 256 # effective batch size is 1024 (256 * 4 GPUs)
  val_batch_size0: 100
  eval_batch_size0: 100
  workers: 10
  persistent_workers: false
  pin_memory: true
image_augmentation:
  random_resized_crop:
    enable: true
    interpolation: "bicubic"
  resize:
    enable: true
    size: 256 # shorter size is 256
    interpolation: "bicubic"
  center_crop:
    enable: true
    size: 224
  random_horizontal_flip:
    enable: true
  rand_augment:
    enable: true
  random_erase:
    enable: true
    p: 0.25
  mixup:
    enable: true
    alpha: 0.2
  cutmix:
    enable: true
    alpha: 1.0
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 224
    crop_size_height: 224
    num_repeats: 1 # change this value for enabling repeated augmentation
loss:
  category: "classification"
  classification:
    name: "cross_entropy"
    label_smoothing: 0.1
optim:
  name: "adamw"
  weight_decay: 0.05
  no_decay_bn_filter_bias: true
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 300
  warmup_iterations: 7500
  warmup_init_lr: 1.e-6
  cosine:
    max_lr: 0.001
    min_lr: 0.00002
model:
  classification:
    name: "vit"
    vit:
      mode: "tiny"
    activation:
      name: "gelu"
  activation:
    name: "gelu"
  layer:
    global_pool: "mean"
    conv_init: "kaiming_uniform"
    linear_init: "trunc_normal"
    linear_init_std_dev: 0.02
ema:
  enable: true
  momentum: 0.0001
stats:
  val: [ "loss", "top1", "top5" ]
  train: ["loss"]
  checkpoint_metric: "top1"
  checkpoint_metric_max: true